export const packages = [
  {
    speed: "5",
    price: "500",
    devices: "2",
    streaming: "light",
    period: "70Gb",
    images: "/images2/wave1.svg",
    validity: "month",
  },
  {
    speed: "8",
    price: "800",
    devices: "6",
    streaming: "Hd",
    period: "140Gb",
    images: "/images2/wave2.svg",
    validity: "month",
  },
  {
    speed: "10",
    price: "1200",
    devices: "4",
    period: "280Gb",
    streaming: "light",
    images: "/images2/wave1.svg",
    validity: "month",
  },

  {
    speed: "5",
    price: "150",
    devices: "2",
    streaming: "2k",
    period: "40Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
  {
    speed: "8",
    price: "200",
    devices: "4",
    streaming: "4k",
    period: "60Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
  {
    speed: "10",
    price: "250",
    devices: "6",
    streaming: "4k",
    period: "80Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
];

export const packages2 = [
  {
    speed: "8",
    price: "7",
    devices: "2",
    streaming: "light",
    period: "Unlimited",
    images: "/images2/wave1.svg",
    validity: "hour",
  },
  {
    speed: "8",
    price: "20",
    devices: "4",
    period: "Unlimited",
    streaming: "light",
    images: "/images2/wave1.svg",
    validity: "3hour",
  },
  {
    speed: "10",
    price: "20",
    devices: "4",
    period: "5Gb",
    streaming: "light",
    images: "/images2/wave1.svg",
    validity: "24hour",
  },
  {
    speed: "5",
    price: "30",
    devices: "2",
    period: "Unlimited",
    streaming: "light",
    images: "/images2/wave1.svg",
    validity: "12hour",
  },
];
