export const packages = [
  {
    speed: "5",
    price: "1",
    devices: "2",
    streaming: "light",
    period: "70Gb",
    images: "/images2/wave1.svg",
    validity: "month",
  },
  {
    speed: "15",
    price: "700",
    devices: "4",
    period: "90Gb",
    streaming: "light",
    images: "/images2/wave1.svg",
    validity: "month",
  },
  {
    speed: "20",
    price: "900",
    devices: "6",
    streaming: "Hd",
    period: "100Gb",
    images: "/images2/wave2.svg",
    validity: "month",
  },
  {
    speed: "5",
    price: "200",
    devices: "2",
    streaming: "2k",
    period: "50Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
  {
    speed: "10",
    price: "400",
    devices: "4",
    streaming: "4k",
    period: "60Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
  {
    speed: "20",
    price: "600",
    devices: "6",
    streaming: "4k",
    period: "70Gb",
    images: "/images2/wave2.svg",
    validity: "week",
  },
];

export const packages2 = [
  {
    speed: "10",
    price: "20 for 1Hour",
    devices: "2",
    streaming: "light",
    period: "Unlimited",
    images: "/images2/wave1.svg",
  },
  {
    speed: "10",
    price: "40 for 3Hours",
    devices: "4",
    period: "Unlimited",
    streaming: "light",
    images: "/images2/wave1.svg",
  },
  {
    speed: "10",
    price: "20 for 2Hours",
    devices: "4",
    period: "2 Gb",
    streaming: "light",
    images: "/images2/wave1.svg",
  },
  {
    speed: "10",
    price: "20 for 3Hours",
    devices: "4",
    period: "4 Gb",
    streaming: "light",
    images: "/images2/wave1.svg",
  },
  {
    speed: "20",
    price: "100 for 24Hours",
    devices: "4",
    streaming: "Hd",
    period: "Unlimited",
    images: "/images2/wave2.svg",
  },
  {
    speed: "20",
    price: "150 for 24Hours",
    devices: "4",
    streaming: "Hd",
    period: "Unlimited",
    images: "/images2/wave2.svg",
  },
];
