export const packages = [
  {
    speed: "5",
    price: "500",
    devices: "2",
    streaming: "720p",
    period: "70Gb",
    images: "/images2/wave1.svg",
    validity: "month",
  },
  {
    speed: "8",
    price: "800",
    devices: "3",
    streaming: "1080p",
    period: "140Gb",
    images: "/images2/wave1.svg",
    validity: "month",
  },
  {
    speed: "10",
    price: "1200",
    devices: "4",
    period: "280Gb",
    streaming: "2160p",
    images: "/images2/wave1.svg",
    validity: "month",
  },

  {
    speed: "5",
    price: "150",
    devices: "2",
    streaming: "720p",
    period: "40Gb",
    images: "/images2/wave1.svg",
    validity: "week",
  },
  {
    speed: "8",
    price: "200",
    devices: "3",
    streaming: "1080p",
    period: "60Gb",
    images: "/images2/wave1.svg",
    validity: "week",
  },
  {
    speed: "10",
    price: "250",
    devices: "4",
    streaming: "2160p",
    period: "80Gb",
    images: "/images2/wave1.svg",
    validity: "week",
  },
];

export const packages2 = [
  {
    speed: "8",
    price: "7",
    devices: "2",
    streaming: "1080p",
    period: "Unlimited",
    images: "/images2/wave1.svg",
    validity: "hour",
    id: 1,
  },
  {
    speed: "8",
    price: "20",
    devices: "2",
    period: "Unlimited",
    streaming: "1080p",
    images: "/images2/wave1.svg",
    validity: "3hour",
    id: 2,
  },
  {
    speed: "10",
    price: "20",
    devices: "2",
    period: "5Gb",
    streaming: "2160p",
    images: "/images2/wave1.svg",
    validity: "24hour",
    id: 3,
  },
  {
    speed: "5",
    price: "30",
    devices: "2",
    period: "Unlimited",
    streaming: "720",
    images: "/images2/wave1.svg",
    validity: "12hour",
    id: 4,
  },
];
